### ISSUE TITLE
Apply the picoc in the embedded system of extreme low resource 

### ISSUE THREAD

**Issue by eeyrw** [zsaleeba/picoc#20]
My target is the ARM processor running with 16kb RAM and 128kb Flash ROM and there is no filesystem. Is it possible to apply the picoc?

**Comment by zsaleeba** [comment]
16KB is probably a bit too small to run picoc, sorry.

--
Zik Saleeba
zik@zikzak.net
 
 
 
On Mon, Jan 25, 2016, at 09:10 PM, eeyrw wrote:
> My target is the ARM processor running with 16kb RAM and 128kb Flash ROM and there is no filesystem Is it possible to apply the picoc?


> —
> Reply to this email directly or view it on GitHub[1]. 


>  


Links:

  1. https://github.com/zsaleeba/picoc/issues/20

**Comment by eeyrw** [comment]
May get by with 128kb RAM ? Could you figure out the approx minimal requirement of picoc?

**Comment by zsaleeba** [comment]
I've run it on an STM32 with 64KB of RAM and 256KB of FLASH.

--
Zik Saleeba
zik@zikzak.net
 
 
 
On Tue, Jan 26, 2016, at 01:13 PM, eeyrw wrote:
> May get by with 128kb RAM ? Could you figure out the approx minimal requirement of picoc?


> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/zsaleeba/picoc/issues/20#issuecomment-174777310
